obj-$(CONFIG_UIO)	+= uio.o
obj-$(CONFIG_UIO_CIF)	+= uio_cif.o
obj-$(CONFIG_UIO_PDRV)	+= uio_pdrv.o
obj-$(CONFIG_UIO_PDRV_GENIRQ)	+= uio_pdrv_genirq.o
obj-$(CONFIG_UIO_DMEM_GENIRQ)	+= uio_dmem_genirq.o
obj-$(CONFIG_UIO_AEC)	+= uio_aec.o
obj-$(CONFIG_UIO_SERCOS3)	+= uio_sercos3.o
obj-$(CONFIG_UIO_PCI_GENERIC)	+= uio_pci_generic.o
obj-$(CONFIG_UIO_NETX)	+= uio_netx.o
obj-$(CONFIG_UIO_PRUSS)         += uio_pruss.o
obj-$(CONFIG_UIO_RTK_SE) += uio_rtk_se.o
obj-$(CONFIG_UIO_RTK_MD) += uio_rtk_md.o
obj-$(CONFIG_UIO_RTK_RBUS) += uio_rtk_rbus.o
obj-$(CONFIG_UIO_RTK_REFCLK) += uio_rtk_refclk.o

#ccflags-y += -DAO_ON_SCPU
#ccflags-y += -I$(srctree)/sound/arm/
#obj-y += uio_rtk_ao.o

