#Copyright (C) 2007-2013 Realtek Semiconductor Corporation.
EXTRA_CFLAGS += -I ../core/
EXTRA_CFLAGS += -I$(srctree)/arch/arm/mach-rtk119x/driver

#ccflags-y += -DAO_ON_SCPU

obj-$(CONFIG_RTD1195_CECTX) += cec0_rtd1195.o
#cectx_rtd1195.o


